name: hockey
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/music/gamesound.mp3
    - assets/sound_efts/menuclick.wav
    - assets/sound_efts/menuback.wav
    - assets/sound_efts/playerhitpuck.mp3
    - assets/sound_efts/ophitpuck.mp3
    - assets/sound_efts/puckhitsides.wav
    - assets/sound_efts/playerscores.wav
    - assets/sound_efts/opscores.wav
    - assets/sound_efts/gameover.wav